### ISSUE TITLE
Watchdog error

### ISSUE THREAD

**Issue by RangerFrank** [zer0TF/cute-comfy#10]
I keep getting this error thrown at me, I've reinstalled watchdog and cute-comfy but something beyond my comprehension is causing issues with detecting and writing the new file.

```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "D:\AI\Stability Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\watchdog\observers\api.py", line 204, in run
    self.dispatch_events(self.event_queue)
  File "D:\AI\Stability Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\watchdog\observers\api.py", line 380, in dispatch_events
    handler.dispatch(event)
  File "D:\AI\Stability Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\watchdog\events.py", line 276, in dispatch
    {
  File "D:\AI\Stability Matrix\Data\Packages\ComfyUI\custom_nodes\cute-comfy\watcher.py", line 120, in on_created
    update_metadata(event.src_path, config_dict)
  File "D:\AI\Stability Matrix\Data\Packages\ComfyUI\custom_nodes\cute-comfy\watcher.py", line 149, in update_metadata
    prompt_positive = get_metadata_clip_text(nodelist, NODE_TITLE_PREFERRED_POSITIVE)
  File "D:\AI\Stability Matrix\Data\Packages\ComfyUI\custom_nodes\cute-comfy\watcher.py", line 194, in get_metadata_clip_text
    return node['widgets_values'][0].replace('\r', '').replace('\n', ' ').strip()
KeyError: 'widgets_values'
```

**Comment by RangerFrank** [comment]
I think it's just python being python.
